"""Add code_snapshots table

Revision ID: 3ccb7ac3e73f
Revises: 
Create Date: 2026-04-03 15:15:38.371369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ccb7ac3e73f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_num', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('snapshot_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_num'], ['homework.num'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_snapshots_homework_user_created', 'code_snapshots', ['homework_num', 'user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_snapshots_homework_user_created', table_name='code_snapshots')
    op.drop_table('code_snapshots')
    # ### end Alembic commands ###
